### ISSUE TITLE
Test request - YC

### ISSUE THREAD

**Issue by yc-lau** [Aurory-Game/aurory-issues#1]
### Problem
Lorem ipsum

### Solution
Lorem ipsum

### Alternatives/workarounds
Lorem ipsum

### Additional context
Lorem ipsum

### Community guidelines
All issues filed in this repository must abide by the [Aurory community guidelines](https://aurory.io/code-of-conduct/).

### How to vote
Please give us a thumbs up or thumbs down as a reaction to help us prioritize this feature. Feel free to comment if you have a particular need or comment on how this feature should work.

**Comment by jp** [comment]
Hello @yc-lau 
Lorem ipsum 2023!
