### ISSUE TITLE
[Bug]: Shiba's basic attack can sometimes generate 2 or even 3 hype points.

### ISSUE THREAD

**Issue by kissiga** [Aurory-Game/aurory-issues#106]
### Contact Details

Simi

### What happened?

Shiba's basic attack can sometimes generate 2 or even 3 hype points.

### Steps to reproduce

I don't know currently.

### Expected Behavior

The basic attack generates 1 hype.

### Screenshots / Videos capture / Attachments

Watch the changes in the hype points of BC and N9:

https://user-images.githubusercontent.com/16439674/216489419-b4348a7f-91c7-4808-a26b-6713adcf753a.mp4

This is another video:

https://user-images.githubusercontent.com/16439674/216489436-9d2c4171-1c1c-4593-81af-22c8e467f713.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment]
@kissiga The 2x Hype gained is from the trigger of Dodge, not the basic attack.
