### ISSUE TITLE
[Bug]: Axo - a triggered Fate Swap generates hype points

### ISSUE THREAD

**Issue by kissiga** [Aurory-Game/aurory-issues#107]
### Contact Details

Simi

### What happened?

I guess a small bug: during the trigger of Axo - Fate Swap hype points were generated by the enemies.

### Steps to reproduce

Use Fate Swap as a reaction.

### Expected Behavior

 Aurory Tactics v0.2.7 10/25/2022

- **Reactions do not reward hype on trigger anymore.** A triggered reaction usually meant you both cancelled an enemy action and made him waste hype. That basically means they lost both time units, hype and opportunity for almost no Hype Cost on the reacting creature side.

https://discord.com/channels/836601552130801676/981554264352636928/1034404633617109014

### Screenshots / Videos capture / Attachments

https://user-images.githubusercontent.com/16439674/216761914-1fa6410e-2e12-4198-a421-9bd69234dd34.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment]
@kissiga The changelog you quoted above was in reference to reactionary abilities previously refunding the Hype cost of when the ability is triggered. It is intended that reactionary abilities still award 2x Hype to all other Nefties as displayed in your video.

Closing out this ticket as per my comment
