### ISSUE TITLE
[Bug]: Axo - Fate Swap didn't replace the HP points correctly

### ISSUE THREAD

**Issue by kissiga** [Aurory-Game/aurory-issues#114]
### Contact Details

Simi

### What happened?

Axobubble probably didn't replace the HP points correctly (video).
1. My Axo had 355 HP, which increased to 396 HP when I ended my turn on the healing field. 
However, after the FateSwap was performed, you can see that Dino was left with 510 HP, instead of 396.

2. Another issue is that my Axo's maximum HP is 554. 
Dino's HP covered this value, so Axo's HP should have been fully restored to its maximum value of 554.
So after FateSwap, it should have had 554-99 (due to the Stomp attack) = 455 HP, not 359.

### Steps to reproduce

The steps are visible in the video.

### Expected Behavior

"if a creature attacks Axobubble, its **current HP** and Hype points are definitely swapped with Axobubble before the attack effect is applied. "
https://discord.com/channels/836601552130801676/981554264352636928/1000117302274039910

After the Stomp attack and the Pressure Bomb side effect, my Axo should have ~423 HP points, not 327.

### Screenshots / Videos capture / Attachments

https://www.dropbox.com/s/b46fv6rmb27f0m7/FateSwap_HP.mp4?dl=0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment]
Hi @kissiga I was able to confirm that Fate Swap is indeed dependent on the % of HP for both Nefties. Closing out this ticket as per my comment.

**Comment by kissiga** [comment]
> Hi @kissiga I was able to confirm that Fate Swap is indeed dependent on the % of HP for both Nefties. Closing out this ticket as per my comment.

Hi @EvanxQA , thank you!
