### ISSUE TITLE
[Bug]: Axo - Defensive Dome - opponent can enter the Dome

### ISSUE THREAD

**Issue by kissiga** [Aurory-Game/aurory-issues#115]
### Contact Details

Simi

### What happened?

ZZoo can enter the Dome using SkyDrop.

### Steps to reproduce

Attack an Axo that is using a shield, with ZZoo's SkyDrop.

### Expected Behavior

By definition, an opponent cannot enter inside the shield. 
So ZZoo should bounce off the shield and shouldn't be able to cause any damage. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment]
@kissiga When attempting to reproduce this issue on our test environment, we can see that Sky Drop does not allow for Zzoo to puncture through Defensive Dome. What we did see happen once or twice (which sounds like what you may be experiencing) is that the Defensive Dome expires just before Zzoo lands, giving the impression that Zzoo actually broke the dome with Sky Drop.

I will close out this ticket as per my comment above
