### ISSUE TITLE
[Feature Request]: Create daily / weekly Quests which incentivize AURY burning mechanisms 

### ISSUE THREAD

**Issue by EvanxQA** [Aurory-Game/aurory-issues#27]
### Contact Details

Evan_XQA

### Problem

Players want to have goals/objectives to focus on for further engagement

### Solution

- Implement Daily/Weekly objectives such as: send X aurorians on an expedition, hatch X eggs, win X games using an NFT Nefty
- Gameplay Challenges can also be implemented: Heal X damage using Blockchoy, knock X enemies using Dinobit
- Rewards can be given for completing milestones

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kissiga** [comment]
I do not find the burning mechanism in this. 
Which/what AURY would be burned?

**Comment by EvanxQA** [comment]
> I do not find the burning mechanism in this. Which/what AURY would be burned?

The burning mechanisms in this case would be sending Aurorians on Expeditions, Hatching Eggs, or buying Nefties via the Marketplace (any method of spending AURY, or purchasing it)
