### ISSUE TITLE
[Feature Request]: Create a levelling system for account profiles. A Battle Pass which you could gain access to by paying AURY, which gives you rewards for gaining profile experience

### ISSUE THREAD

**Issue by EvanxQA** [Aurory-Game/aurory-issues#28]
### Contact Details

Evan_XQA

### Problem

Players want to have goals/objectives to focus on for further engagement

### Solution

Implement a profile levelling system that produces rewards based on profile XP/level. Also include an optional Battle Pass that players can also purchase for additional rewards as they level up

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jp** [comment]
@martineliii please add a thumbs up on the original post to vote on the issue.
<img width="433" alt="image" src="https://user-images.githubusercontent.com/929189/212963221-ae06b9e1-8e1b-4517-a284-32599edff01d.png">
