### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by JohnnyAurory** [Aurory-Game/aurory-issues#3]
### Affects versions
List the version you are running, and any other versions you have attempted a recreated. 

### Platform
(Please complete the following information)
 - Device: [e.g. Desktop, iPhone X, Pixel 3, etc]
 - OS: [e.g. iOS, macOS, Windows ME]
 - Browser + version [e.g. chrome, safari plus a version]
 - Wallet [Phantom | Ledger, etc] & and version

### Community guidelines
All issues filed in this repository must abide by the [Aurory community guidelines](https://aurory.io/code-of-conduct/).

**Comment by jp** [comment]
I'm sorry Johnny, we will not fix the test issues 😝
