### ISSUE TITLE
[Feature Request]: Create incentive for inviting new players to play Tactics / become active players

### ISSUE THREAD

**Issue by EvanxQA** [Aurory-Game/aurory-issues#39]
### Contact Details

Evan_XQA

### Problem

Have a way to increase traffic and exposure to the title with a constant influx of new players

### Solution

Implement an invite/referral system that would rewards existing players to invite/refer potential new players

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kissiga** [comment]
In Web 3.0 it would be quite difficult to prevent some people from abusing such a system.
Even if possible, it is resource intensive I don't know if it would pay off or not.
