### ISSUE TITLE
[Feature Request]: Add chat in Aurory Tactics 

### ISSUE THREAD

**Issue by TimAurory** [Aurory-Game/aurory-issues#44]
### Contact Details

AuroTim #9909

### Problem

It's not easy to exchange with our opponents during or after a game. Many players don't have the same name at their discord ID, so we can't congratulate them, or give them advice. 

### Solution

Adding a direct chat in the game would be nice. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kissiga** [comment]
I like the idea very much.
Think about those who would be bothered by it. 
It would be nice if we could turn it off and/or hide it.

**Comment by megalaks** [comment]
Chats are almost always disabled in game in games I like this, I think it is a very bad idea. 
But emotes could be used like in all other games like this. 
Limit it to 1 or 2 emotes per minute. and make it customizable.

**Comment by Doudou9455** [comment]
I think it's a good idea! Especially not to focus on bad players etc. ... in all online games there will be bad players who will insult, rage etc. ... 
But I think that this minority should not prevent to put a chat to be able to exchange with the opponent, start with a "Gl Hf" "Nice play" or finish with a "GG"
