### ISSUE TITLE
[Feature Request]: observer mode

### ISSUE THREAD

**Issue by kissiga** [Aurory-Game/aurory-issues#46]
### Contact Details

Simi#2465

### Problem

It would be good to be able to watch how others play.
Especially the beginner players can learn a lot from better players without having to play with them but it is also exciting to watch the top players play.

### Solution

Need an observer mode. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by megalaks** [comment]
Personally I think this should be Optional. 
I would not like to give my strategies away, if I want them to be secret. O_O 
Last season I often refrained from using strong moves early season, to not "spread" the info. 
It's not that I don't want to teach new playes to play. and I do sometimes help new players with learning the basics, or even advanced tactics. but if there is some little cool trick, or a certain variation of a move, on a specific map. That I want to keep secret for an upcoming tournament, I would not want it to be revealed.

**Comment by kissiga** [comment]
It is understandable and you are absolutely right. 
It should be optional.
