### ISSUE TITLE
[Feature Request]: Tie the ability to use a certain default nefty to a Tutorial for the nefty that needed to be completed

### ISSUE THREAD

**Issue by megalaks** [Aurory-Game/aurory-issues#54]
### Contact Details

megalaks#2806

### Problem

I think people should be assisted in learning the basics of a unit before using it, so they do not get frustrated. 

### Solution

A potential solution could be [...]

Every unit should have a tutorial associated with. 
You can let me design the tutorials if you want to outsource the job :) I can make some good ones that explains the units abilities and weaknesses. 

If you just skip ahead of a tutorial, you will not complete the tutorial because you will DIE!! 
You have to do the correct moves to complete the tutorials successfully. and then you will unlock a 40% default for the Nefty associated with that given tutorial.
These small tutorials will not be super hard. but will simply explain some basic tactics that you need to learn to understand the game. 

First 3 is mandatory for a new account. (Bitebit,Dipking,Dino) the rest are Optional. but needs to be completed if you want the use that neftys default version. 

Further make the option to disable default nefties, so you don't missclick by accident. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kissiga** [comment]
I am afraid that this could be a disadvantage for those who just want to try the game quickly.
In other words I think it's a big advantage for Aurory that people can play without registration or any other things. 
Just a few clicks, and anyone can play on a real battlefield, which is great imo.

But I like the idea very much!

What do you think about an alternative:
People would receive rewards for completing the tutorial, like: 
- a simple skin for that Nefty (which represents that it has passed the turorial)
- boosted TOKE rewards for the Nefty if the player passes the turorial

 note to the last one: 
 - everyone who did pass the test would get the same TOKE reward/win **as now**
 - everyone who did not pass the test would get slightly less TOKE reward/win
 
So it would be in everyone's interest to complete the tutorial successfully even if it's not mandatory.

**Comment by megalaks** [comment]
@kissiga 
As it is right now, new people actually cannot just play the game, They already needs to complete the tutorial to play. 
I'm suggesting that we include one more mandatory quick tutorial with dinobit. and from here on make everyone optional. 
But I don't think people like trying a new game that they do not understand. and just get wrecked 20 or maybe 50 times in a row because they do not understand the game. 
So by having the tutorials connected to unlocking nefties, we can reward new players in an interesting way, for learning the basics.
To make it clear, I do not suggest that people will be able to use 0% nefties if they have not completed a tutorial. 
If a user have not completed a tutorial yet for a given Nefty, that nefty will just be greyed out. with the text: Unlock "Number9" by completing tutorial. and if the user completes it. they can use it as a 40% avg nefty. 

I like your suggestion of small rewards for completing tutorials too. But they will probably not have any real value as bots can just create new accounts and complete as many tutorials as they like.

**Comment by kissiga** [comment]
@megalaks thanks for the explanation. 

> They already needs to complete the tutorial to play.

Didn't know that lol🤦‍♂️ 

>  nefty will just be greyed out. with the text: Unlock "Number9" by completing tutorial. and if the user completes it. they can use it as a 40% avg nefty.

Like it 👍 👍
