### ISSUE TITLE
[Bug]: Incorrect Hype values on the Nefty selection page

### ISSUE THREAD

**Issue by kissiga** [Aurory-Game/aurory-issues#55]
### Contact Details

Simi#2465

### What happened?

On the Nefty selection page there are incorrect Hype values.

SPV - Selection page value
CV -  Correct value (in-game)

I highlight the wrong values.

BlockChoy
SPV: **5**/7/**7**/**10**
RV: 6/7/8/13

Dinobit
SPV: **8**/5/**8**/15
RV: 9/5/9/15

Dipking
SPV: 8/7/**7**/15
RV:  8/7/6/15

Shiba
SPV: 6/**8**/10/12
RV: 6/10/10/12

ZZoo
SPV: 4/**8**/**7**/9
RV: 4/6/9/9

Unika
SPV: **6**/6/**6**/**9**
RV: 7/6/5/12

Bitebit, Number 9 and AxoBubble values are correct.

### Steps to reproduce

Go to Nefty selection page.

### Expected Behavior

It is expected to see the correct values.

### Screenshots / Videos capture / Attachments

![wrong_hype_values](https://user-images.githubusercontent.com/16439674/213165610-d27dca3a-b161-4cfe-b9f4-796415659057.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kissiga** [comment]
Sorry a few hours ago I checked to see if there was a report of this problem but there wasn't, and I didn't check again before sending it so it was duplicated. 
@megalaks report: https://github.com/Aurory-Game/aurory-issues/issues/52

**Comment by jp** [comment]
Thanks @kissiga, please don't forget to upvote on the other report by adding a 👍 on the top post. This will help us to sort and prioritize the issues.
