### ISSUE TITLE
[Bug]: minimum cost of a round can be <3 TU

### ISSUE THREAD

**Issue by kissiga** [Aurory-Game/aurory-issues#57]
### Contact Details

Simi#2465

### What happened?

The basic rule: the minimum cost of a round is 3 TU can be breached depending on the power of the overcharge.

### Steps to reproduce

Get enough hype, do an overcharged attack without movements, check the timeline.

### Expected Behavior

If this is not intentional, the minimum cost of a round should be 3 TU.

### Which browsers are you seeing the problem on?

Chrome

### Which wallet are you using?

Solflare

### Screenshots / Videos capture / Attachments

If the rule would apply, Dino should be on the timeline after opponent B, but that's not what happens.

![overcharge_turnmincost png](https://user-images.githubusercontent.com/16439674/213284879-a770d947-1ab5-4227-9788-62474de6f40e.jpg)
![overcharge_turnmincost_2 png](https://user-images.githubusercontent.com/16439674/213284891-b05c9188-d2fd-49df-b597-1ddee521cb28.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by megalaks** [comment]
I thought this was on purpose o_O 
I always do it to decrease minimum TU

**Comment by EvanxQA** [comment]
@kissiga This is as intended. If you overcharge an ability it provides Initiative and therefore it can reduce the amount of TU used that turn to less than 3.

**Comment by kissiga** [comment]
Sorry for the false report and thank you for the clarification.
