### ISSUE TITLE
[Bug]: Dipking - Jumpscare cannot be dodged by Slippery skin / Dodge

### ISSUE THREAD

**Issue by kissiga** [Aurory-Game/aurory-issues#58]
### Contact Details

Simi#2465

### What happened?

Jumpscare cannot be dodged by Slippery skin / Dodge.

### Steps to reproduce

Start game.
Proceed to Lobby.
Proceed to Kitty’s Tavern.
Proceed to PVP battle.
P1: Make sure Slippery skin status is on Dipking or Dodge is activated
P2: Accumulate enough hype to cast Jumpscare.
P2: Attack Dipking with Jumpscare.
Observe the result.

### Expected Behavior

Dodge / Slippery skin works as intended against aoe skills.

### Which browsers are you seeing the problem on?

Chrome

### Which wallet are you using?

Solflare

### Screenshots / Videos capture / Attachments

https://user-images.githubusercontent.com/16439674/213441279-d9b768a8-c219-45f2-b94d-32b0888e89f4.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment]
@kissiga Jumpscare is not meant to be able to be dodged by "Dodge". It is able to be dodged by Slippery Skin (not displayed in your video). We do have an issue for the ectoplasm stack remaining on the Dipking visually, but the damage is still dodged by Slippery Skin.
