### ISSUE TITLE
[Feature Request]: Lending / Rev Sharing System.

### ISSUE THREAD

**Issue by R00001** [Aurory-Game/aurory-issues#66]
### Contact Details

R.#7332

### Problem

A Lending / Reward Sharing System must be in place in order to get big players(lenders) / Small guys (ftp players).

Whales finnaly would have the chance to get their resources to work and players that dont wanna invest // have a wallet get the chance to use better suited / choosen nefties for their current strat.

### Solution

As far I can think of and taking into account that different nefties will have different APY, there are 2 possible solutions:

### A: Lending.-:

The lending solution could be done by mirroring some parts of protocols like yawwn lending (https://www.yawww.io/loans/listings),

First, the lender deposit into SyncSpace the neftie. then he creates the lending offer (this happens on-chain), if the offer gets taken the neftie gets locked till the lending period expires then he can claim the Aury from the borrower.

As and the idea of the parameters for the lend creation:

-Aury/day (APY* (*there is no such thing as APY since there is no FP))
-Loan duration (in days)

Borrowers will pay the offer (neftie Loan_duration*Aury_day) set by the lender upfront (on-chain) and will have the right to use that neftie that gets tied temporarily to its sync space (game) account.

Once the loan ends, the lender should be able to Re-lend on one transaction (able to change parameters, so prob the same instruction as lending but checking its a relend) (this is done for them to be able to automatize lending).

### B: Reward Sharing:

Its a similar lending system but here the offer is done by the players (Axie player farms system)

So players offer which % of gains they will share, and you should be able to see the current rating of that player, their win rate, etc.

Lenders should be able to filter (or even have the option to auto lend) for X winrate , Y rat, and Z rev-share.

this way players don't pay upfront. Higher rat/winrate players will be able to choose a higher % for themselves and low rat players will have to lower as much % to compete against other players to get nefties (note that on axie Bullrun players would be as low as 20% rev-share from axie managers).

But the axie system was kinda bad since there was no lending** marketplace, we have the chance to do it right.

and as you can imagine this system relies on synspace as the authority to verify that the player setting the offer has X rat and Y winrate.

Note that B has a higher hype potential (easier to understand for a player that they can borrow and share what they win rather than ``I have to pay to play but now they call it lending``), plus players dont need a wallet since all could be done on syncspace (potentially, judge yourself)

free it's free and it's what a lot of players want.

Note A: to be able to lend/share a neftie it should be at 10/10 OKANERGY.
Note B: Lender should be able to cancel if the player doesn't meet/spend the Energy requirements/drop X rating / lowers its win rate by X amount...

![Group 35](https://user-images.githubusercontent.com/70406417/213703529-1a962efd-6044-4341-a742-fcc1db20b8e2.png)

(Here an idea of how the rev share UI could look like to get you guys some ideas)

### Additional context

This was think top of my head and on a questionable english, might dig deeper into the the details of the Rev Sharing system if you guys like the idea, but i think its better if you develop from this since you know all the tech details that an idea like this needs to take off and we don't, (i could go into sync space repo and get something better... but... time.).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by R00001** [comment]
Oh! and down the line you need to lower the Aury distribution for TOKE and OKA to fit in this system.

**Comment by BouncyAus** [comment]
This is actually well thought out from only the top of your head mate. The seed idea needs to be planted for the team to want to grow from it. I entirely support this idea, I would favor idea B for personal choice, however I think both can work if done correctly. This would bring much more value to players wanting to dig deeper into the Auroryverse.

**Comment by kissiga** [comment]
Thanks for taking the time to think about these things and for the sharing.
My first thought is that I would prefer version B.

**Comment by megalaks** [comment]
I like the B-option most. But I think rewards will need to be a bit bigger for this to make sense. 
Right now it would probably be better to play with default nefties, than to rent a nefty and make, lets say 30% less. 
It's a super cool thought to automate it, in a simple way.

**Comment by PavelStehno** [comment]
Thanks for writing this up.
I agree Revenue sharing is better system for guilds. 
  - It allows players to try things for free.
  - It is a win-win if done well.
  - It could be done via SyncSpace.

**Suggestion about wallets**:
 - Guild should be able to own NFTs on a Ledger protected wallet.
 - Then the guild syncs the assets into their SyncSpace guild account via SyncSpace.
 - All the guild interactions like accepting players, choosing nefties and sharing rewards should be offchain via SyncSpace.
 
 **Aurorians too**
 - Currently I cannot use my Burning Helios in game because such a valuable NFT will never be in a hot wallet. 
 - If our guild (behind Ledger wallet) is setup, I could wear my Helios ingame avatar in my play account (non-legder hot wallet) and not risk anything.
