### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by SolBluesky** [Aurory-Game/aurory-issues#70]
### Contact Details

Sol_Bluesky#0218

### Problem

Imbalanced matchmaking

### Solution

A potential solution could be [...]
I hope there will be a feature where if a 1k ranker fights a 1.6k, if the 1k loses, it only lose 10 rating instead of 20. Or if the 1k wins, it gains more rating than the usual.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jp** [comment]
Helle, please see here about details on the matchmaking: https://github.com/Aurory-Game/aurory-issues/issues/42
