### ISSUE TITLE
[Bug]: Turn order according to Initiative stats

### ISSUE THREAD

**Issue by GrMonteCristo** [Aurory-Game/aurory-issues#76]
### Contact Details

MonteCristo

### What happened?

I have Dipking (DjDhHCKCzZnwhaCAzcsY2qCqaK9SY6i8gPofVDD8MHP3) whose Initiative is 96%, and Bitebit (H7mTT2RkCzG1BRhYY7THajVUQXorEDMyVuCkTs6zKrGf) whose INI is 94%. In the battle Bitebit's turn is always before Dipking.

### Steps to reproduce

Steps to reproduce:
1. Select Bitebit (H7mTT2RkCzG1BRhYY7THajVUQXorEDMyVuCkTs6zKrGf), Dipking (DjDhHCKCzZnwhaCAzcsY2qCqaK9SY6i8gPofVDD8MHP3) and 3rd nefty.
2. Start the match.

### Expected Behavior

The Bitebit will go before Dipking.

### Which browsers are you seeing the problem on?

Chrome

### Which wallet are you using?

Phantom

### Screenshots / Videos capture / Attachments

![Снимок экрана 2023-01-23 в 14 13 29](https://user-images.githubusercontent.com/122971798/214026997-cd42764a-42c0-457f-adc0-8e25b3841a31.png)
![Снимок экрана 2023-01-23 в 14 12 37](https://user-images.githubusercontent.com/122971798/214027017-782c5403-8244-4fcc-bd20-eea2e7de17ff.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment]
@GrMonteCristo When taking a look into this, it appears that team ordering is indeed decided by which Nefty has the highest Initiative stat. Is it possible to send me a screenshot of the Battle ID in the lower left corner of the screen, so that I can look into the logs of the battle and determine what might be happening?

**Comment by GrMonteCristo** [comment]
![Снимок экрана 2023-01-25 в 13 55 02](https://user-images.githubusercontent.com/122971798/214554367-8c556be9-5f40-401e-b643-45c30e2adacb.png)

**Comment by EvanxQA** [comment]
Closing out this issue as per my comment above. Will reopen this ticket should there be additional reports of this issue, or if this issue is reproduced internally.
