### ISSUE TITLE
[Bug]: N9 - After SStrike, the marked sign/badge does not disappear

### ISSUE THREAD

**Issue by kissiga** [Aurory-Game/aurory-issues#85]
### Contact Details

Simi#2465

### What happened?

After N9 SStrike, the marked sign/badge does not disappear.

### Steps to reproduce

Use SStrike.

### Expected Behavior

 CHANGE: Scarring Strike
   • Removes the Passession mark from the target

### Screenshots / Videos capture / Attachments

You can see in the video that I can't attack my opponent in the middle, but the marked sign is there. 
So it works as expected but the badge should disappear.
https://user-images.githubusercontent.com/16439674/215203288-0978857a-f790-4214-be9f-41ac37e0c0b4.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment]
The status icon which remains after using Scarring Strike is related to the defense debuff, not the ectoplasm stack.
Closing out this issue as per my comment.
