### ISSUE TITLE
[Bug]: Zzoo - Ultimate ability gives only 2 Hype

### ISSUE THREAD

**Issue by kissiga** [Aurory-Game/aurory-issues#89]
### Contact Details

Simi#2465

### What happened?

Zzoo - Ultimate ability gives only 2 Hype

### Steps to reproduce

Try Zoo - Sky Drop

### Expected Behavior

Ultimate abilities give you 3 Hype points.

### Screenshots / Videos capture / Attachments

https://user-images.githubusercontent.com/16439674/215283501-e86010de-3ff2-43fb-829e-540c3cf69a8d.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment]
This was raised in the past and deemed to be as designed by the designer.
