### ISSUE TITLE
[Bug]: Axo defensive dome expiring feels random. The 8 TUs is hard to understand (applies to Scarry strike too).

### ISSUE THREAD

**Issue by PavelStehno** [Aurory-Game/aurory-issues#95]
### What happened?

I played defensive dome with Axo.
Next turn I made a simple attack and didn´t move. (should cost 3,5 TUs as I have 108 Initiative). 
So there should be still 4,5 TUs of defensive dome, right? 
However I ended turn and the Dome expired. 

Opponent Zoo simply came and killed me.

There are 3 issues here: 
1) the 8 TUs looks bugged 
2) it should be clarified when the 8 TUs counter start. 
    a) When casted? 
    b) at the end of turn of neftie that casted it? 
3) It is hard to understand for players how this works... It feels preferable to use more deterministic descriptions like "for 1 hit" (in case of a scary strike) or "for 2 turns" (in case of Defensive Dome)

### Steps to reproduce

cast Axo Defensive Dome and count TUs 

### Expected Behavior

as above

### Which browsers are you seeing the problem on?

Chrome

### Which wallet are you using?

Phantom

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by EvanxQA** [comment]
@kissiga Scarring Strike defensive debuff will only expire once the victim has spent 8TU. In your video, Unika is stunned by Stomp and is pushed down the timeline, postponing the start of Unika's turn. The defense down debuff will remain until 8TU is spent by  Unika, and the snare will only last 1 turn (taken by Unika)
